language: ruby

cache:
 bundler: true
 directories:
  - node_modules
  - vendor/assets/node_modules

rvm:
  - 2.3.1

before_script:
  - rvm list
  - ./bin/rake db:create RAILS_ENV=test
  - ./bin/rake ridgepole:apply RAILS_ENV=test
  - ./bin/rake npm:install
