name: Ruby
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  spec:
    runs-on: ubuntu-latest
    name: Run test
    services:
      postgres:
        image: circleci/postgres:10.6-alpine
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: dmemo_test
      mysql:
        image: circleci/mysql:5.6
        ports: ["3306:3306"]
        env:
          MYSQL_DATABASE: dmemo_test
    env:
      PG_HOST: localhost
      RAILS_ENV: test
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '20'
        cache: 'npm'
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: .ruby-version
        bundler-cache: true
    - name: Setup DB
      run: bin/rails db:create ridgepole:apply
    - name: Setup npm packages
      run: npm install
    - name: Compile assets
      run: npm run webpack
    - name: Run Zeitwerk check
      run: bin/rake zeitwerk:check
    - name: Run rspec
      run: bin/rspec
