name: Ruby
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  spec:
    runs-on: ubuntu-latest
    name: Run test
    services:
      postgres:
        image: postgres:16
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: dmemo_test
          POSTGRES_HOST_AUTH_METHOD: trust
      mysql:
        image: mysql:8.4
        ports: ["3306:3306"]
        env:
          MYSQL_DATABASE: dmemo_test
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    env:
      PG_HOST: localhost
      RAILS_ENV: test
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: .ruby-version
        bundler-cache: true
    - name: Setup DB
      run: bin/rails db:create ridgepole:apply
    - name: Setup npm packages
      run: npm install
    - name: Compile assets
      run: npm run webpack
    - name: Run Zeitwerk check
      run: bin/rake zeitwerk:check
    - name: Run rspec
      run: bin/rspec
